apps/books/urls.py
from django.urls import path
from .views import *

app_name = 'books'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('books/', BookListView.as_view(), name='book-list'),
    path('book-Detail/<slug:slug>', BookDetailView.as_view(), name='book-detail'),
    path('book-Detail-create/<int:id>', CreateReviewView.as_view(), name='create-review'),
    path('book-Detail-update/<int:id>', UpdateReviewView.as_view(), name='update-review'),
    path('book-Detail-delete/<int:id>', DeleteReviewView.as_view(), name='delete-review'),
    path('book-Genre/<int:id>', BookGenreView.as_view(), name='book-genre'),
    path('book-Author-detail/<int:id>', BookAuthorDetailView.as_view(), name='book-author'),
    path('book-Authors/', BookAuthorListView.as_view(), name='book-authors'),
    path('book-Add-Author/', AddAuthorView.as_view(), name='add-author'),
    path('book-Add-Book/', AddBookView.as_view(), name='add-book'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.books.urls')),
    path('user', include('apps.users.urls')),
]

urlpatterns += static(settings.STATIC_URL)#, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/books/models.py
from django.db import models
from apps.shared.models import AbstractBaseModel
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
import random

class LanguageChoices(models.TextChoices):
    ENGLISH = 'en', "English"
    FRANCE = 'fr', "France"
    RUSSIAN = 'ru', 'Russian'
    ARABIC = 'ab', 'Arabic'
    UZBEK = 'uz', 'Uzbek'


class BookGenre(AbstractBaseModel):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

class BookAuthor(AbstractBaseModel):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    birthdate = models.DateField()
    website = models.URLField()
    avatar = models.ImageField(upload_to='authors/avatar', null=True, default='default/author_img/author.png')
    about = models.TextField()
    email = models.EmailField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(AbstractBaseModel):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    published = models.DateField()
    isbn = models.CharField(max_length=120)
    language = models.CharField(max_length=7, choices=LanguageChoices.choices, default=LanguageChoices.ENGLISH)
    page = models.IntegerField()
    cover = models.ImageField(upload_to="books/cover", null=True, default='default/book_img/book.png')
    genre = models.ManyToManyField(BookGenre, "books")
    authors = models.ManyToManyField(BookAuthor, "books")

    def __str__(self):
        return self.title

class BookReview(AbstractBaseModel):
    book = models.ForeignKey("books.Book", models.CASCADE, "reviews")
    user = models.ForeignKey("users.User", models.CASCADE, "reviews")
    body = models.TextField()
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    like_count = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.user} --> {self.book}"

apps/books/forms.py
from django import forms
from apps.books.models import BookReview, BookAuthor, Book
from apps.books.models import LanguageChoices
from django.template.defaultfilters import slugify

class CreateReviewForm(forms.ModelForm):
    rating = forms.IntegerField(min_value=1, max_value=5)
    body = forms.Textarea()

    class Meta:
        model = BookReview
        fields = ('body', 'rating', 'like_count')
        


    
class AddBookAuthorForm(forms.ModelForm):
    class Meta:
        model = BookAuthor
        fields = ('first_name', 
                  'last_name', 
                  'birthdate', 
                  'website', 
                  'avatar', 
                  'about')

class AddBookForm(forms.ModelForm):
    title = forms.CharField()
    descriptions = forms.Textarea()
    published = forms.DateField()
    isbn = forms.IntegerField()
    language = forms.ChoiceField(choices=LanguageChoices)
    page = forms.IntegerField()
    cover = forms.FileField()
    class Meta:
        model = Book
        fields = ('title',
                  'slug',
                  'description', 
                  'published',
                  'isbn', 
                  'language', 
                  'page',
                  'cover',
                  'genre', 
                  'authors')
        widgets = {
            "title":forms.TextInput(attrs={"placeholder":"book title"}),
            "description":forms.Textarea(attrs={"placeholder":"book description"}),
            "published":forms.DateInput(attrs={"placeholder":"book published date"}),
            "isbn":forms.NumberInput(attrs={"placeholder":"book isbn"}),
            "page":forms.NumberInput(attrs={"placeholder":"book page"}),
            "cover":forms.FileInput(attrs={"placeholder":"book image"}),
        }

apps/books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, TemplateView, CreateView
from django.views import View
from apps.users.models import User
from apps.books.models import Book, BookGenre, BookReview, BookAuthor
from .forms import CreateReviewForm, AddBookAuthorForm, AddBookForm
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from django.contrib import messages



class HomePageView(View):
    def get(self, request):
        books = Book.objects.all()
        recomendet_books = books.order_by('id')[:4]
        return render(request, "home.html", {
            "recomendet_books":recomendet_books,
            "corusel_books":books.order_by('created_at'),
            # "videos":...,
            "featured_books":...
        })
    

class BookListView(View):
    def get(self, request):
        books = Book.objects.all()

        page = request.GET.get('page', 1)
        size = request.GET.get('size', 3)
        paginator = Paginator(books.order_by('id'), size)
        page_obj = paginator.page(page)
        return render(request, 'books/book_list.html', {
            "page_obj":page_obj, 
            "corusel_books":books.order_by('-created_at')
        })


class BookDetailView(View):
    def get(self, request, slug):
        book = Book.objects.get(slug=slug)
        form = CreateReviewForm()
        return render(request, "books/book_detail.html", 
                      {
                          "book":book,
                          "form":form,
                          "count_reated":"4.0",
                          "count_reviews":"34",
                          "count_likes":"233"
                      })


class CreateReviewView(View):

    def post(self, request, id):
        book = Book.objects.get(id=id)
        user = User.objects.get(username=request.user.username)

        form = CreateReviewForm(request.POST)

        if form.is_valid():
            BookReview.objects.create(
                user = user,
                book = book,
                body = form.cleaned_data.get("body"),
                rating = form.cleaned_data.get("rating")
            )
            messages.success(request, "Creating new review")
            return redirect(reverse("books:book-detail", kwargs={"slug":book.slug}))
        else:
            messages.warning(request, "Your review is not valid !")
            context = {
                "book":book,
                "form":form
            }
        return render(request, "books/book_detial.html", context=context)

class UpdateReviewView(View):
    def get(self, request, id):
        reviews = get_object_or_404(BookReview, id=id)
        form = CreateReviewForm(request.POST, instance=reviews)
        return render(request, "books/update_review.html", {"form":form})
    
    def post(self, request, id):
        review = BookReview.objects.get(id=id)
        form = CreateReviewForm(request.POST, instance=review)
        if form.is_valid():
            messages.success(request, "Review succesffuly updated")
            form.save()
            return redirect(reverse("books:book-detail", kwargs={"slug":review.book.slug}))
        messages.warning(request, "your updating review is not valid")
        return render(request, reverse("books:book-detail", kwargs={"slug":review.book.slug}), {"form":form})
        

class DeleteReviewView(View):
    def get(self, request, id):
        review = get_object_or_404(BookReview, id=id)
        return render(request, "books/delete_review.html", {"review":review})
    
    def post(self, request, id):
        review = get_object_or_404(BookReview, id=id)
        messages.success(request, "Review succesffully deleted")
        review.delete()
        return render(request, reverse("books:book-detail", kwargs={"slug":review.book.slug}), {"review":review})



class BookGenreView(View):
    def get(self, request, id):
        genre = BookGenre.objects.get(id=id)
        books = Book.objects.filter(genre=genre)
        # print(genre)
        return render(request, "books/book_list.html", {
            "page_obj":books
        })


class BookAuthorListView(ListView):
    model = BookAuthor
    template_name = 'books/author_list.html'
    context_object_name = 'authors'

class BookAuthorDetailView(View):
    def get(self, request, id):
        author = BookAuthor.objects.get(id=id)
        return render(request, "books/book_authors_detail.html", {
            "author":author,
        })
    

class AddAuthorView(CreateView):
    form_class = AddBookAuthorForm
    template_name = 'books/add_author.html'
    context_object_name = 'form'
    success_url = reverse_lazy('books:home')
    
    # def get(self, request):
    #     form = AddBookAuthorForm()
    #     return render(request, "books/add_author.html", {"form":form})
    
    # def post(self, request):
    #     form = AddBookAuthorForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('books:home')
    #     return render(request, 'books/add_author.html')

class AddBookView(CreateView):
    form_class = AddBookForm
    template_name = 'books/add_book.html'
    context_object_name = 'form'
    success_url = reverse_lazy('books:home')
    # def get(self, request):
    #     form = AddBookForm()
    #     return render(request, "books/add_book.html", {"form":form})

    # def post(self, request):
    #     form = AddBookForm(request.POST)
    #     if form.is_valid():
    #         Book.objects.create(
    #             slug  =  slugify(form.cleaned_data.get('title')),
    #         )
    #     return render(request, "books/add_book.html")

templates/books/add_author.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Add author {% endblock %}

{% block content %}
<div class="container">
    <div class="title">
        <h3>
            add Author *
        </h3>
    </div>
    <form action="{% url 'books:add-author' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn ">save</button>
    </form>
</div>
{% endblock %}

templates/books/add_book.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Add book {% endblock %}

{% block content %}
<div class="container">
    <div class="title">
        <h3>
            add Book *
        </h3>
    </div>
    <form action="{% url 'books:add-book' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>
</div>
{% endblock %}

templates/books/author_list.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Book Detail {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/book-filter.css' %}" />
{% endblock %}

{% block content %}
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><a href="{% url 'books:home' %}" style="color: #6c5dd4">Home</a></li>
    <li><a href="{% url 'books:book-list' %}" style="color: #6c5dd4">Books</a></li>
    <li><a href="#">Authors</a></li>
  </ul>
</div>
<section class="filter">
  <div class="book-grid-container">
    <div class="book-collections">
      <h4>Book Authors *</h4>
      <div class="books">
        {% for author in authors %}
        <div class="book-card">
          <div class="img">
            <a href="{% url 'books:book-author' author.id %}"><img src="{{ author.avatar.url }}" alt="img" /></a>
            <button class="like" id="likebtn">
              <i class="fa-regular fa-heart"></i>
            </button>
          </div>
          <h4>{{ author.first_name }} {{ author.last_name }}</h4>
          <small>{{ author.birthdate }}</small>
        </div>
        {% endfor %}
      </div>
      {% include 'includes/base_paginator.html' %}
    </div>
  </div>
</section>
<!-- <br>
<h4><center>Authors</center></h4>
<hr>
<div class="card-group">
    {% for author in authors %}
    <div class="card my-4">
        <center>
            <img src="{{ author.avatar.url }}" class="img-fluid" alt="...">
        </center>
      <div class="my-4">
        <div class="card-body">
          <a href="{% url 'books:book-author' author.id %}">
            <h5 class="card-title">{{ author.first_name }} {{ author.last_name }}</h5>
          </a>
        </div>
      </div>
  </div>
    {% empty %}
    <h3>Now auhtor</h3>
    {% endfor %}
  </div>
<hr> -->
<script src="{% static 'js/repeat-js.js' %}"></script>
{% endblock %}

templates/books/book_authors_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Book Detail {% endblock %}

{% block content %}
<h3>Author page</h3>
  <div class="row mt-5">
    <div class="col-3">
        <img src="{{ author.avatar.url }}" class="img-fluid" alt="...">
    </div>
    <div class="col-6">
      <h2>
        {{ author.first_name }} {{ author.last_name }}
      </h2><hr>
      <small>website: </small>
      <a href="{{ author.website }}">{{ author.website }}</a><br>
      <span><small>birthdate: </small></span>
      <small>{{ author.birthdate }}</small>
      <hr><center>About</center>
      <p>{{ author.about }}</p>
      <hr>
    </div>
  </div>

<section class="book-sale">
  <div class="heading">
    <h4>books {{ author.first_name }} {{ author.last_name }} *</h4>
    <div class="arrowbtn">
      <i id="left" class="fa-solid fa-angle-left"></i>
      <i id="right" class="fa-solid fa-angle-right"></i>
    </div>
  </div>
  <div class="book-container">
    <div class="wrapper">
      <ul class="carousel">
        {% for book in author.books.all %}
        <li class="card">
          <div class="img">
            <a href="{% url 'books:book-detail' book.slug %}"><img src="{{ book.cover.url }}" alt="" /></a>
            <span class="badge">50%</span>
          </div>
          <h5>The Giver</h5>
          <div class="genre">
            <span>
              {% for genre in book.genre.all %}
                {{ genre.name }}
              {% endfor %}
            </span>
          </div>
          <div class="footer">
            <span class="star"><i class="fa fa-star"></i> 4.7</span>
          </div>
        </li>
        {% empty %}
        <h3>now books</h3>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
<!-- <h3>Author page</h3>
  <div class="row mt-5">
    <div class="col-3">
        <img src="{{ author.avatar.url }}" class="img-fluid" alt="...">
    </div>
    <div class="col-6">
      <h2>
        {{ author.first_name }} {{ author.last_name }}
      </h2><hr>
      website: 
      <a href="{{ author.website }}">{{ author.website }}</a><br>
      birthdate: 
      <small>{{ author.birthdate }}</small>
      <p>{{ author.about }}</p>
      <hr>
    </div>
  </div>
  <center><br><h4>Author books</h4><br></center>
  {% for book in author.books.all %}
    <div class="col-3 my-4 mt-5">
      <img src="{{ book.cover.url }}" alt="img">
    </div>
    <div class="col-6">
      <a href="{% url 'books:book-detail' book.slug %}">{{ book.title }}</a>
    </div>
  {% endfor %} -->
  
{% endblock %}

templates/books/book_detail.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Book Detail {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/book-filter.css' %}" />
{% endblock %}

{% block content %}
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><a href="{% url 'books:home' %}" style="color: #6c5dd4">Home</a></li>
    <li><a href="{% url 'books:book-list' %}" style="color: #6c5dd4">Books</a></li>
    <li><a href="#">Book detail</a></li>
  </ul>
</div>
  <section class="book-overview">
    <div class="img">
      <img src="{{ book.cover.url }}" alt="" />
    </div>
    <div class="book-content">
      <h4>{{ book.title }}</h4>
      <div class="meta">
        <div class="review"> 
          <div class="rating">
            <span>{{ count_reated }}</span>
          </div>
          <div class="comment-like">
            <small
              ><img src="{% static 'images/comment.png' %}" alt="" /> <span>{{ count_reviews }} Reviews</span></small
            >
            <small><img src="{% static 'images/like.png' %}" alt="" /> <span>{{ count_likes }}k Likes</span></small>
          </div>
        </div>
        <div class="social-btn">
          <a href=""><i class="fa-brands fa-facebook-f"></i>Facebook</a>
          <a href=""><i class="fa-brands fa-twitter"></i>Twitter</a>
          <a href=""><i class="fa-brands fa-whatsapp"></i>Whatsapp</a>
          <a href=""><i class="fa-regular fa-envelope"></i>Email</a>
        </div>
      </div>
     <p>{{ book.description }}</p>
      <p><h5>isbn :</h5>{{ book.isbn }}</p>
      <div class="footer">
        <div class="author-detail">
          <div class="author">
            <small>Written by</small>
            <strong>
                {% for author in book.authors.all %}
                <a href="{% url 'books:book-author' author.id %}">
                    {{ author.first_name }} {{ author.last_name }}
                </a>
                {% endfor %}
            </strong>
            <small>genres</small>
            <strong>
              {% for genre in book.genre.all %}
              <a href="{% url 'books:book-genre' genre.id %}">
                <span>{{ genre.name }}</span>
              </a>
              {% endfor %}
            </strong>
          </div>
          <div class="year">
            <small>Year</small>
            <strong>{{ book.published }}</strong>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% if user.is_authenticated %}
  <div class="container mt-4">
    <div class="card-title">
      <h3>Write review</h3>
    </div>
    <form action="{% url 'books:create-review' book.id %}" method="post">
      {% csrf_token %}
      <small>body</small>
      <div class="row my-3 mt-4">{{ form.body }}</div>
      <small>rating</small>
      <div class="row my-3 mt-4">{{ form.rating }}</div>
      <small>like</small>
      <div class="row my-3 mt-4">{{ form.like_count }}</div>
      <button type="submit">save</button>
    </form>
  </div>
  {% endif %}
  <hr>
<div class="container">
  <div class="row">
    <h3>Reviews</h3>
    <div class="col-9">
        {% for review in book.reviews.all %}
            <div class="card my-2">
                <div class="card-header">
                    {{ review.user.username }} rated {{ review.rating }}
                    {% if request.user.id == review.user.id %}
                    <span>
                      <a href="{% url 'books:update-review' book.id %}">
                        <button class="btn btn-light" style="color: powderblue">update</button>
                      </a>
                    </span>
                    <span>
                      <a href="{% url 'books:delete-review' book.id %}">
                        <button class="btn btn-light" style="color: red">delete</button>
                      </a>
                    </span>
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="#">
                            {{ review.user.username }}
                        </a>
                    </h5>
                    <p class="card-text">{{ review.body }}</p>
                    <a href="#" class="btn btn-light">Like 👍</a> <span class="fw-lighter">{{ review.like_count }} likes </span>
                </div>
            </div>
        {% empty %}
        Now review
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}

templates/books/book_list.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Books {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/book-filter.css' %}" />
{% endblock %}

{% block content %}
<div class="breadcrumb-container">
  <ul class="breadcrumb">
    <li><a href="{% url 'books:home' %}" style="color: #6c5dd4">Home</a></li>
    <li><a href="#">Books</a></li>
  </ul>
</div>

<section class="filter">
  <div class="book-grid-container">
    <div class="book-collections">
      <h4>Books</h4>
      <div class="books">
        {% for book in page_obj %}
        <div class="book-card">
          <div class="img">
            <a href="{% url 'books:book-detail' book.slug %}"><img src="{{ book.cover.url }}" alt="img" /></a>
            <button class="like" id="likebtn">
              <i class="fa-regular fa-heart"></i>
            </button>
          </div>
          <h5>{{ book.title }}</h5>
          <div class="star-rating">
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
          </div>
        </div>
        {% endfor %}
      </div>
      {% include 'includes/base_paginator.html' %}
    </div>
  </div>
</section>
{% include 'includes/carusel_books.html' %}
<!-- <script src="{% static 'js/back-to-top.js' %}"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script> -->
<!-- <script src="{% static 'js/script.js' %}"></script> -->
<script src="{% static 'js/repeat-js.js' %}"></script>
<!-- <script src="{% static 'js/add-to-cart.js' %}"></script> -->
<!-- <script src="https://code.jquery.com/jquery-3.6.3.js"></script> -->
{% endblock %}

templates/books/delete_review.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Add author {% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        <h3>Delete it is review</h3>
        {% csrf_token %}
        <button type="submit">delete</button>
        <a href="{% url 'books:book-detail' review.book.slug %}"><button>now</button></a>
    </form>
</div>
{% endblock %}

templates/books/update_review.html
{% extends 'base_.html' %}
{% load static %}
{% block title %} Add author {% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">update</button>
    </form>
</div>
{% endblock %}