apps/books/urls.py
from django.urls import path
from .views import *

app_name = 'books'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('books/', BookListView.as_view(), name='book-list'),
    path('book-Detail/<slug:slug>', BookDetailView.as_view(), name='book-detail'),
    path('book-Detail-create/<int:id>', CreateReviewView.as_view(), name='create-review'),
    path('book-Detail-update/<int:id>', UpdateReviewView.as_view(), name='update-review'),
    path('book-Detail-delete/<int:id>', DeleteReviewView.as_view(), name='delete-review'),
    path('book-Genre/<int:id>', BookGenreView.as_view(), name='book-genre'),
    path('book-Author-detail/<int:id>', BookAuthorDetailView.as_view(), name='book-author'),
    path('book-Authors/', BookAuthorListView.as_view(), name='book-authors'),
    path('book-Add-Author/', AddAuthorView.as_view(), name='add-author'),
    path('book-Add-Book/', AddBookView.as_view(), name='add-book'),
]

apps/users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView

app_name = 'users'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.books.urls')),
    path('user', include('apps.users.urls')),
]

urlpatterns += static(settings.STATIC_URL)#, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!--- google font link-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <!-- Bootstrap link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Fontawesome Link for Icons -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
    {% block head %}{% endblock %}
 
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
</head>
<body>
    <header>
      <nav class="navbar">
        <div class="logo">
          <div class="img">
            <img src="{% static 'images/logo.png' %}" alt="" />
          </div>
          <div class="logo-header">
            <h4><a href="{% url 'books:home' %}">Goodreads clone</a></h4>
            <small>welcome goodreads</small>
          </div>
        </div>
        <ul class="nav-list">
          <div class="logo">
            <div class="title">
              <div class="img">
                <img src="{% static 'images/logo.png' %}" alt="" />
              </div>
              <div class="logo-header">
                <h4><a href="{% url 'books:home' %}">Bookoe</a></h4>
                <small>Book Store Website</small>
              </div>
            </div>
            <button class="close"><i class="fa-solid fa-xmark"></i></button>
          </div>
          <li><a href="{% url 'books:home' %}">Home</a></li>
          <li><a href="{% url 'books:book-list' %}">Books</a></li>
          <li><a href="{% url 'books:book-authors' %}">Authors</a></li>
          {% if user.is_authenticated %}
          <li><a href="#">Bookshelves</a></li>
          <li><a href="{% url 'books:add-book' %}"><h3>add book</h3></a></li>
          <li><a href="{% url 'books:add-author' %}"><h3>add author</h3></a></li>
          <li><a href="{% url 'users:profile' request.user.id %}">Profile</a></li>
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
          {% else %}
          <button class="login"><a href="{% url 'users:login' %}">Log In</a></button>
          <button class="signup">
            <i class="fa-solid fa-user"></i><a href="{% url 'users:register' %}">Sign Up</a>
          </button>
          {% endif %}
        </ul>
        <div class="hamburger">
          <div class="line"></div>
          <div class="line"></div>
          <div class="line"></div>
        </div>
      </nav>
    </header>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        <p>{{ message }}</p>
    </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
    <footer>
      <div class="container">
        <div class="logo-description">
          <div class="logo">
            <div class="img">
              <img src="{% static 'images/logo.png' %}" alt="" />
            </div>
            <div class="title">
              <h4>Gooodreads</h4>
              <small>welcome goodreads</small>
            </div>
          </div>
          <div class="logo-body">
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magnam
              voluptates eius quasi reiciendis recusandae provident veritatis
              sequi, dolores architecto dolor possimus quos
            </p>
          </div>
          <div class="social-links">
            <h4>Follow Us</h4>
            <ul class="links">
              <li>
                <a href=""><i class="fa-brands fa-facebook-f"></i></a>
              </li>
              <li>
                <a href=""><i class="fa-brands fa-youtube"></i></a>
              </li>
              <li>
                <a href=""><i class="fa-brands fa-twitter"></i></a>
              </li>
              <li>
                <a href=""><i class="fa-brands fa-linkedin"></i></a>
              </li>
              <li>
                <a href=""><i class="fa-brands fa-instagram"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="categories list">
          <h4>Book Categories</h4>
          <ul>
            <li><a href="Pages/book-filter.html">Action</a></li>
            <li><a href="Pages/book-filter.html">Adventure</a></li>
            <li><a href="Pages/book-filter.html">Comedy</a></li>
            <li><a href="Pages/book-filter.html">Crime</a></li>
            <li><a href="Pages/book-filter.html">Drama</a></li>
            <li><a href="Pages/book-filter.html">Fantasy</a></li>
            <li><a href="Pages/book-filter.html">Horror</a></li>
          </ul>
        </div>
        <div class="quick-links list">
          <h4>Quick Links</h4>
          <ul>
            
            <li><a href="#">About Us</a></li>
            <li><a href="#">Books</a></li>
            <li><a href="#">Authors</a></li>
            {% if user.is_authenticated %}
            <li><a href="#">Profile</a></li>
            <li><a href="#">Bookshelves</a></li>
            <li><a href="#">Logout</a></li>
            {% else %}
            <li><a href="#">Login</a></li>
            <li><a href="#">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </footer>
    <button class="back-to-top"><i class="fa-solid fa-chevron-up"></i></button>
    <script src="{% static 'js/back-to-top.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/repeat-js.js' %}"></script>
    <script src="{% static 'js/add-to-cart.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js"></script>
  </body>
</html>

templates/base_.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        Bootstrap demo
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>
<body>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        <p>{{ message }}</p>
    </div>
    {% endfor %}
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col mt-4 my-5">
                    <h3>Title</h3>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum, veniam architecto? Hic, repellendus voluptatum alias praesentium, ab pariatur quia eveniet perferendis quod dolor eum consequatur cumque officiis! Velit, facilis ipsam.</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
<section class="suggestion">
    <div class="container">
      <div class="recommend">
        <h4>Recommended books For You</h4>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Id,
          exercitationem.Lorem ipsum dolor sit amet.
        </p>
        <div class="book-container">
          {% for book in recomendet_books %}
          <div class="book">
            <figure>
              <a href="{% url 'books:book-detail' book.slug %}"
                ><img src="{{ book.cover.url }} " alt=""
              /></a>
            </figure>
          </div>
          {% endfor %}
        <div class="circle-1"></div>
        <div class="circle-2"></div>
      </div>
  </section>

  <section class="sale">
    <div class="header">
      <h4>Videos</h4>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. <br />
        Ipsum dignissimos quasi aliquid numquam.
      </p>
    </div>
    <div class="book-container">
      {% for video in videos %}
      <div class="book">
        <div class="img">
          <a href="#">
            <img src="{{ video.video.url }}" alt="" />
          </a>
        </div>
        <h5>{{ video.title }}</h5>
        <small>{{ video.genre }}</small>
      </div>
      {% empty %}
      <h3>Now videos</h3>
      {% endfor %}
    </div>
  </section>
  {% include 'includes/carusel_books.html' %}
  <section class="feature">
    <div class="main">
      <div class="content">
        <h4>Featured Books</h4>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. <br />
          Molestias, illum? Doloremque eius quis officiis rerum pariatur.
        </p>
      </div>
      <div class="book-section">
        <div class="container">
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-2.jpg' %}" alt="" /></a>
          </div>
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-1.jpg' %}" alt="" /></a>
          </div>
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-3.jpg' %}" alt="" /></a>
          </div>
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-4.jpg' %}" alt="" /></a>
          </div>
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-5.jpg' %}" alt="" /></a>
          </div>
          <div class="img">
            <a href="pages/book-detail.html"><img src="{% static 'images/book-6.jpg' %}" alt="" /></a>
          </div>
        </div>
      </div>
    </div>
    <div class="circle-1"></div>
    <div class="circle-2"></div>
  </section>

  <section class="news">
    <div class="heading">
      <div class="title">
        <h4>Latest News</h4>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. <br />
          Quia, laborum ad perspiciatis ab, sequi.
        </p>
      </div>
      <div class="btn">
        <button>View More <i class="fa-solid fa-arrow-right"></i></button>
      </div>
    </div>
    <div class="news-container">
      {% for news in latest_news %}
      <div class="post">
        <div class="img">
          <img src="{% static 'images/news-1.avif' %}" alt="" />
        </div>
        <h5>Why reading is important for our children?</h5>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Aspernatur, quo temporibus! Tenetur...
          <a href="">Continue reading</a>
        </p>
        <div class="post-footer">
          <div class="img">
            <img src="images/man1.png" alt="" />
          </div>
          <div class="details">
            <strong>James Bond</strong>
            <small>5 August 2020</small>
          </div>
        </div>
      </div>
      {% empty %}
      <h3>Now news</h3>
      {% endfor %}
    </div>
  </section>

  <section class="countdown">
    <div class="container">
      <div class="customer counter">
        <div class="icon">
          <i class="fa-solid fa-user-group"></i>
        </div>
        <div class="content">
          <h4 class="count">125,663</h4>
          <small>Happy Customers</small>
        </div>
      </div>
      <div class="book counter">
        <div class="icon">
          <i class="fa-solid fa-book"></i>
        </div>
        <div class="content">
          <h4 class="count">50,672</h4>
          <small>Book Collections</small>
        </div>
      </div>
      <div class="store counter">
        <div class="icon">
          <i class="fa-solid fa-store"></i>
        </div>
        <div class="content">
          <h4 class="count">1,562</h4>
          <small>Our Stores</small>
        </div>
      </div>
      <div class="writer counter">
        <div class="icon">
          <i class="fa-solid fa-feather"></i>
        </div>
        <div class="content">
          <h4 class="count">457</h4>
          <small>Famous Writer</small>
        </div>
      </div>
    </div>
  </section>
{% endblock %}